version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/client_manager
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
      - HELEKET_PROJECT_URL=${HELEKET_PROJECT_URL:-https://api.heleket.sandbox}
      - HELEKET_MERCHANT_ID=${HELEKET_MERCHANT_ID:-local-merchant}
      - HELEKET_API_KEY=${HELEKET_API_KEY:-local-api-key}
      - HELEKET_WEBHOOK_SECRET=${HELEKET_WEBHOOK_SECRET:-local-webhook-secret}
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health && curl -fsS http://localhost:5000/payouts/webhook/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=client_manager
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mongodb_data:
  rabbitmq_data: