#!/bin/sh

echo "Verificando código antes de enviar..."

# Verificar estilo de código com flake8
echo "Executando flake8 para verificar todo o código..."
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

# Verificar se há erros
if [ $? -ne 0 ]; then
  echo "Há problemas no código. Corrija antes de enviar."
  exit 1
fi

# No futuro, podemos adicionar testes unitários aqui
# python -m unittest discover

echo "Pré-push passou com sucesso!"